/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package soulcrushed;

import org.junit.jupiter.api.Test;

import io.github.Boromoi.soulcrushed.SoulCrushed;

import static org.junit.jupiter.api.Assertions.*;

class SoulCrushedTest {
    @Test void appHasAGreeting() {
        SoulCrushed classUnderTest = new SoulCrushed();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
